POST /admin/api/2024-04/metafields.json
{
  "metafield": {
    "namespace": "global",
    "key": "trustpilot_review",
    "value": 4.3,
    "type": "number_decimal",
    "owner_resource": "shop",
    "owner_id": 123456789  # Remplace avec l'ID de ta boutique
  }
}