# POST http://127.0.0.1:3333/api/product/update/painting HTTP/1.1
# content-type: application/json

# {
#     "type": "painting",
#     "productId": 8827943354715,
#     "ratio": "square",
#     "variant": {
#         "title": "100x100 cm/Toile/Bordure blanche"
#     }
# }



POST http://127.0.0.1:3333/api/product/update/tapestry HTTP/1.1
content-type: application/json

{
    "type": "tapestry",
    "productId": 9317711741275,
    "variant": {
        "title": "100cm x 120cm"
    },
    "cm2": 12000
}