version: '3.8'
services:
  app:
    image: ${DOCKERHUB_USERNAME}/app:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx:latest
    ports:
      - '80:80'
      - '443:443' 
    volumes:
      - /etc/letsencrypt/live/${DIGITALOCEAN_HOST}/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/${DIGITALOCEAN_HOST}/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - app
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db-data:
