name: Deploy to DigitalOcean with Docker

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            if [ -d "/opt/MyselfMonArt_Backend" ]; then
              cd /opt/MyselfMonArt_Backend
              git pull
            else
              cd /opt
              git clone https://github.com/GuetarniWalid/MyselfMonArt_Backend.git
            fi

   
      - name: Install or update Node.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            apt-get install -y nodejs
            npm install -g n
            n stable


      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /opt/Myselfmonart_Backend
            npm install
              




    #   - name: Checkout code
    #     uses: actions/checkout@v4

      # - name: Transfer Docker directory to server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.DIGITALOCEAN_HOST }}
      #     username: ${{ secrets.DIGITALOCEAN_USERNAME }}
      #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      #     source: "./Docker"
      #     target: "/opt/dashboard_myselfmonart"

      # - name: Deploy the app, nginx and database
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DIGITALOCEAN_HOST }}
      #     username: ${{ secrets.DIGITALOCEAN_USERNAME }}
      #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      #     script: |
      #       apt-get update
      #       apt-get install docker-compose -y
      #       cp /opt/dashboard_myselfmonart/.env /opt/dashboard_myselfmonart/Docker/.env
      #       cd /opt/dashboard_myselfmonart/Docker
      #       docker-compose pull
      #       docker-compose up -d
